### ISSUE TITLE
How to use this module in IE 11 and below

### ISSUE THREAD

**Issue by IEfucker** [franciscop/brownies#19]
Using your module for a while, and it helped me a lot.

But recently find it difficult being used in old browser

When I add this module to [transpileDependencies](https://cli.vuejs.org/guide/browser-compatibility.html#browserslist), an error is thrown by babel
`"export 'local' was not found in 'brownies'`

and an error in browser 
`Cannot set property 'brownies' of undefined`

I searched for a while and found it's a problem of babel, it seems to happen in [many other modules](https://github.com/vuejs/vue-cli/issues/1248).

But I don't quite get the point the difference form the module which worked fine and  how to fix this, would you please give some help

**Comment by IEfucker** [comment]
And is there any way to ship Proxy API, which is used in your code

**Comment by franciscop** [comment]
Unfortunately Proxy() is [not compatible with IE 11-](https://caniuse.com/#feat=proxy) and there's no way to define a generic polyfill for a generic library like this. Also, the only way this library's API is possible is thanks to Proxy().

However you _might_ be able to find a polyfill for your specific app. I haven't tried any implementation so I cannot be of much help, sorry. This library uses and supports ES6+ only, [the minified code](https://github.com/franciscop/brownies/blob/master/brownies.min.js) is still ES6.
